[general]
name = "Breaking News Finder"
email = "your.email@example.com"

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0E1117"
textColor = "#FAFAFA"
font = "sans serif"



[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501
address = "0.0.0.0"
